<a href="https://colab.research.google.com/github/iami0npkr/Story/blob/main/Complete_numpy_tutorial_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy - Numerical Python

#Advantages of Numpy Arrays (Numerical Python)
   1. Allows several Mathematical Operations
   2. Faster operations

In [3]:
import numpy as np

List vs Numpy - Time Taken

In [4]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i*5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001210402999999971


Time take by numpy array

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array *=5 # np_array = np_array * 5

end_time = process_time()

print(end_time - start_time)

0.00018762100000024873


Numpy Arrays

In [ ]:
# list

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array

a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [5]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial placeholders in numy arrays

In [6]:
# create a numy array of Zeroes
x = np.zeros((4,5))
print(x)
#

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# create a numy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [10]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# create a numy array with random values
b = np.random.random((3,4))
print(b)

[[0.81901472 0.06879383 0.02792375 0.45945019]
 [0.67496689 0.78076791 0.62786013 0.55004312]
 [0.69120102 0.81209595 0.50686232 0.64533974]]


In [19]:
# random integer values array
c = np.random.randint(10,165,(3,5))
print(c)

[[ 42  34  19  89  50]
 [ 43 161 162  48  32]
 [ 82 115  97  63  91]]


In [20]:
# array of evenly spaced values  -- SPECIFYING THE NUMBER OF VALUES REQUIRED
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [21]:
#array of evenly spaced values > secifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

# Analysing a numpy array

In [23]:
c = np.random.randint(10,90,(5,5))
print(c)

[[88 53 35 46 50]
 [78 85 86 88 54]
 [86 86 73 42 52]
 [57 65 36 14 35]
 [72 71 37 68 34]]


In [24]:
# array dimension
print(c.shape)

(5, 5)


In [25]:
# number of dimensions
print(c.ndim)

2


In [26]:
# number of elements in an array
print(c.size)

25


In [27]:
# checking the data type of the values in the array
print(c.dtype)


int64


#Mathematical operation on a np array

In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [33]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)

[[2 0 4]
 [4 7 8]
 [7 9 7]]
[[11 19 15]
 [14 10 14]
 [19 11 10]]
[[13 19 19]
 [18 17 22]
 [26 20 17]]


In [34]:
print(a-b)
print(a*b)
print(a/b)

[[ -9 -19 -11]
 [-10  -3  -6]
 [-12  -2  -3]]
[[ 22   0  60]
 [ 56  70 112]
 [133  99  70]]
[[0.18181818 0.         0.26666667]
 [0.28571429 0.7        0.57142857]
 [0.36842105 0.81818182 0.7       ]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 19 19]
 [18 17 22]
 [26 20 17]]
[[ -9 -19 -11]
 [-10  -3  -6]
 [-12  -2  -3]]
[[ 22   0  60]
 [ 56  70 112]
 [133  99  70]]
[[0.18181818 0.         0.26666667]
 [0.28571429 0.7        0.57142857]
 [0.36842105 0.81818182 0.7       ]]


#Array Manipulation

In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 0 9]
 [6 5 9]]
(2, 3)


In [37]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 6]
 [0 5]
 [9 9]]
(3, 2)


In [38]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 6]
 [0 5]
 [9 9]]
(3, 2)


In [39]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 6 6]
 [7 3 2]]
(2, 3)


In [42]:
b= a.reshape(3,2)
print(b)
print(b.shape)

[[0 6]
 [6 7]
 [3 2]]
(3, 2)
